#!/bin/bash
killall -q polybar
killall -q sxhkd
killall -q clipmenud

##  --- VARIABLES ---------------------------------

INTERNAL_MONITOR="eDP"
HDMI_PORT="HDMI-A-0"
DISPLAYPORT="DisplayPort-0"
EXTERNAL_MONITOR=$DISPLAYPORT
EXTERNAL_MONITOR_2=$HDMI_PORT	
INTERNAL_MONITOR_ARCH="HDMI-0"

##  --- Init Configuration ----------------
##  --- Keyboard
setxkbmap eu
setxkbmap -option caps:escape

##  --- Mouse
xsetroot -cursor_name left_ptr

##  --- BSPWM configuration ---------------------------
bspc config border_width         0
bspc config window_gap           3
bspc config top_padding          40
bspc config bottom_padding       6
bspc config split_ratio          0.49
bspc config borderless_monocle   true
bspc confir gapless_monocle      true


if [ $(hostnamectl chassis) == "laptop" ]; then

	if [ $(xrandr | grep -o '\bconnected' | wc -l) -eq 3 ]; then
 
		if [ "$(xrandr | grep "$HDMI_PORT" | awk '{print $2}')" == "connected" ] && [ "$(xrandr | grep "$DISPLAYPORT" | awk '{print $2}')" == "connected" ]; then

			EXTERNAL_MONITOR=$DISPLAYPORT
			EXTERNAL_MONITOR_2=$HDMI_PORT
	    fi	
			##  --- Monitor configuration ----------------------
			xrandr --auto
			xrandr --output "$INTERNAL_MONITOR" --rate 60
			xrandr --output "$EXTERNAL_MONITOR" --rate 60 --left-of "$INTERNAL_MONITOR"
			xrandr --output "$EXTERNAL_MONITOR_2" --rate 60 --left-of "$EXTERNAL_MONITOR"
			
		  	##  --- BSPWM workspaces by monitor ------------------
		  	bspc monitor "$EXTERNAL_MONITOR_2" -d I II III
		    bspc monitor "$EXTERNAL_MONITOR" -d IV V VI
			bspc monitor "$INTERNAL_MONITOR" -d VII VII IX

			bspc wm --reorder-monitors "$EXTERNAL_MONITOR_2" "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"

			
			##  --- Polybar init -----------------------------------
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-left &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-center &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-wifi &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-ethernet &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-right &
		
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-banner &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-VPN &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-center &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-music &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-right &
			
			MONITOR=$EXTERNAL_MONITOR_2 polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-banner &
			MONITOR=$EXTERNAL_MONITOR_2 polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-VPN &
			MONITOR=$EXTERNAL_MONITOR_2 polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-center &
			MONITOR=$EXTERNAL_MONITOR_2 polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-music &
			MONITOR=$EXTERNAL_MONITOR_2 polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-right &
		
	elif [ $(xrandr | grep -o '\bconnected' | wc -l) -eq 2 ]; then
 
		if [ $(xrandr | grep "$HDMI_PORT" | awk '{print $2}') == "connected" ]; then
			EXTERNAL_MONITOR=$HDMI_PORT
	    fi	
			##  --- Monitor configuration ----------------------
			xrandr --auto
			xrandr --output "$INTERNAL_MONITOR" --rate 60
			xrandr --output "$INTERNAL_MONITOR" --rate 60 --left-of "$EXTERNAL_MONITOR"
			
		  ##  --- BSPWM workspaces by monitor ------------------
			bspc monitor "$EXTERNAL_MONITOR" -d I II III IV V
			bspc monitor "$INTERNAL_MONITOR" -d VI VII VIII IX X
			bspc wm --reorder-monitors $EXTERNAL_MONITOR $INTERNAL_MONITOR
			
			##  --- Polybar init -----------------------------------
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-left &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-center &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-wifi &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-ethernet &
			polybar -c $HOME/configFiles/polybar/thinkpad-II.conf thinkpad-right &
		
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-banner &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-VPN &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-center &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-music &
			MONITOR=$EXTERNAL_MONITOR polybar -c $HOME/configFiles/polybar/thinkpad-II.conf II-right &
	else
		xrandr --auto

		##  --- Monitor configuration ----------------------
		xrandr --output "$INTERNAL_MONITOR" --rate 60
		
		bspc wm --reorder-monitors $INTERNAL_MONITOR
		##  --- BSPWM workspaces by monitor ------------------
		bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
		
		# Move all windows from the now-nonexistent monitor to the internal one follow the current desktop 
		for wid in $(bspc query -N -n .window); do
		#	CURRENT_MONITOR=$(bspc query -M -n "$wid" --names)
		#	if [ "$CURRENT_MONITOR" != "$INTERNAL_MONITOR" ]; then
				CURRENT_DESKTOP=$(bspc query -D -n "$wid" --names)
				bspc node "$wid" --to-monitor "$INTERNAL_MONITOR" -d "$CURRENT_DESKTOP"
		#	fi
		done
		
		##  --- Polybar init -----------------------------------
		polybar -c $HOME/configFiles/polybar/thinkpad.conf left &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf banner &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf wifi &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf ethernet &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf bspwm &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf music &
		polybar -c $HOME/configFiles/polybar/thinkpad.conf right &

	fi

else
	            
 ##  --- Monitor configuration ----------------------
 xrandr --output "$INTERNAL_MONITOR_ARCH" --rate 60
 bspc monitor "$INTERNAL_MONITOR_ARCH" -d I II III IV V VI VII VIII IX X
 
 ##  --- Polybar init --------------------
 polybar -c $HOME/configFiles/polybar/arch.conf  left &
 polybar -c $HOME/configFiles/polybar/arch.conf  banner &
 polybar -c $HOME/configFiles/polybar/arch.conf  ethernet &
 polybar -c $HOME/configFiles/polybar/arch.conf  bspwm &
 polybar -c $HOME/configFiles/polybar/arch.conf  right &
 polybar -c $HOME/configFiles/polybar/arch.conf  music &
 feh --bg-scale $HOME/Pictures/Wallpapers/hyundai.png

fi

##  --- Software and Services --------------------------
sxhkd -c $HOME/configFiles/sxhkd/sxhkdrc &
picom --config $HOME/configFiles/picom/picom.conf &
feh --bg-scale $HOME/Pictures/Wallpapers/hyundai.png
clipmenud &
